<?php

/**
 * @file
 * Module file for conference_api.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function conference_api_form_alter(
  &$form,
  FormStateInterface $form_state,
  $form_id
) {
  \Drupal::service('conference_api.form_helper')->alter($form, $form_state, $form_id);
}

/**
 * Implements hook_theme().
 */
function conference_api_theme() {
  return [
    'conference_api_conference_info' => [
      'variables' => [
        // The conference.
        'conference' => NULL,
      ],
    ],
    'conference_api_conference_entity_list' => [
      'variables' => [
        // The conference.
        'conference' => NULL,
        // The entity type.
        'type' => NULL,
        // The entities.
        'entities' => NULL,
      ],
    ],
  ];
}
