<?php

namespace Drupal\os2conticki_content;

use Drupal\Core\TypedData\DataDefinitionInterface;
use Drupal\Core\TypedData\TypedData;
use Drupal\Core\TypedData\TypedDataInterface;
use InvalidArgumentException;

/**
 *
 */
class ConferenceAppComputed extends TypedData {

  /**
   * {@inheritdoc}
   */
  public function __construct(DataDefinitionInterface $definition, $name = NULL, TypedDataInterface $parent = NULL) {
    parent::__construct($definition, $name, $parent);

    if ($definition->getSetting('property') === NULL) {
      throw new InvalidArgumentException("The definition's 'property' key has to specify the name of the property to be rendered.");
    }
  }

  /**
   *
   */
  public function getValue() {
    $property = $this->definition->getSetting('property');

    switch ($property) {
      case 'icons':
        return $this->getIcons();
    }

    // TODO: Change the autogenerated stub.
    return parent::getValue();
  }

  /**
   *
   */
  private function getIcons() {
    $item = $this->getParent();
    return [
      1, 2, 3,
    ];
  }

}
