<?php

/**
 * @file
 * Module file for os2conticki_app.
 */

/**
 * Implements hook_theme().
 */
function os2conticki_app_theme() {
  return [
    'os2conticki_app_app' => [
      'variables' => [
        // The conference.
        'conference' => NULL,
        // The base url,.
        'basename' => NULL,
        // The app manifest url.
        'manifest_url' => NULL,
        // General app data.
        'app_data' => NULL,
        // App icons.
        'icons' => NULL,
        'application_name' => NULL,
        // The conference api url.
        'api_url' => NULL,
        'app_stylesheets' => NULL,
        'app_scripts' => NULL,
        'service_worker_url' => NULL,
        // Rendered tracking code.
        'tracking' => NULL,
      ],
    ],
    'os2conticki_app_service_worker' => [
      'variables' => [
        'precache_key' => 'os2conticki-app-cache',
        // Urls to pre-cache.
        'precache_urls' => NULL,
      ],
    ],
    'os2conticki_app_tracking_siteimprove' => [
      'variables' => [
        'key' => NULL,
      ],
    ],
  ];
}
