#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/../" && pwd)

git_tag=${1:-}
if [ -z "$git_tag" ]; then
	(>&2 echo "Usage: $0 git-tag")
	exit
fi

source_dir=/tmp/display-react
target_dir=$dir/libraries/display-react

rm -fr $source_dir
git clone --branch "$git_tag" https://github.com/OS2ConTicki/display-react $source_dir
version=$(git -C $source_dir describe --abbrev=0)

if [ -n "$version" ]; then
  sed -i '' "s/  version:.*/  version: $version/" "$dir/os2conticki_app.libraries.yml"
fi

mkdir -p "$target_dir/public"
rsync -azv --delete $source_dir/public/dist "$target_dir/public"
