#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dir=$(cd $(dirname "${BASH_SOURCE[0]}")/../ && pwd)
bold=$(tput bold)
normal=$(tput sgr0)

git_tag=${1:-}
if [ -z "$git_tag" ]; then
	(>&2 echo "Usage: $0 git-tag")
	exit
fi

cd $dir
rm -fr /tmp/display-react
git clone --branch $git_tag https://github.com/OS2ConTicki/display-react /tmp/display-react
version=$(git -C /tmp/display-react describe --abbrev=0)

if [ ! -z "$version" ]; then
  sed -i '' "s/  version:.*/  version: $version/" $dir/os2conticki_app.libraries.yml
fi

mkdir -p libraries/display-react/public
rsync -azv --delete $TMPDIR/display-react/public/dist libraries/display-react/public
